version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"  # Replace with actual user/group IDs
    networks:
      - jellyfin_network
    ports:
      - "8096:8096"
      - "8920:8920"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - /Users/sabeeh/Documents/Jellyfin:/config
      - /Users/sabeeh/Documents/Jellyfin:/cache
      - type: bind
        source: /Users/sabeeh/Documents/Jellyfin
        target: /media
    restart: 'unless-stopped'

networks:
  jellyfin_network:
    driver: bridge
